name = "zinima"
description = "Your awesome title"
license = "MIT"
homepage = "https://github.com/boxdot/zinima"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
site = { author = "GitHub User", email = "your-email@domain.com" }

[author]
name = "boxdot"
homepage = "https://zerovolt.org"

[original]
author =  "jekyll"
homepage = "https://jekyll.github.io/minima/"
repo = "https://github.com/jekyll/minima"
